In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('public_trip_data.csv')
df.head()
trip_ids = df["TripID"]

In [4]:
df.describe()

,TripID,ShippingType,EntitiyCode,HotelNights,NetCosts,Departure_CO2e,Return_CO2e,Hotel_CO2e,Spend_CO2e,TotalCO2e,HighCarbon
count,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000,65289.000000
mean,43574.366509,11.384567,8011.104474,2.936237,2151.651886,1326.672254,1326.430958,74.616441,1618.949794,2727.719653,0.250057
std,25105.293053,2.488487,1414.067067,1.426505,1049.117452,1384.375971,1384.302135,65.805207,1524.417153,2766.271867,0.433049
min,1.000000,4.000000,6000.000000,1.000000,300.000000,0.000000,0.000000,6.700000,0.000000,6.700000,0.000000
25%,21818.000000,10.000000,7000.000000,2.000000,1200.000000,376.822886,328.042478,31.200000,431.823967,830.135410,0.000000
50%,43563.000000,12.000000,8000.000000,3.000000,2400.000000,931.146675,931.146675,49.000000,1183.643136,1894.493350,0.000000
75%,65308.000000,13.000000,9000.000000,4.000000,3000.000000,1708.458757,1708.458757,102.800000,2453.798762,3472.917514,1.000000
max,87053.000000,17.000000,10000.000000,6.000000,3900.000000,10503.746080,10503.746080,353.400000,14459.460390,21202.492160,1.000000

In [5]:
df.drop('TripID',axis=1 , inplace=True)
df = df.drop(columns=["EmployeeNumber"])

In [6]:
df

,DepartureLocationCountry,DepartureLocationCity,ArrivalLocationCountry,ArrivalLocationCity,ShippingType,ShippingTypeDescription,Purpose,OutOfPolicy,EntitiyCode,BusinessUnit,HotelNights,NetCosts,Departure_CO2e,Return_CO2e,Hotel_CO2e,Spend_CO2e,TotalCO2e,HighCarbon
0,CN,Beijing,IN,New Delhi,12,Business Class Flight,Customer Visit,No,9000,Services,1,900,1565.121857,1565.121857,58.9,1472.279257,3189.143714,0
1,US,New York,MX,Mexico City,11,First Class Flight,Customer Visit,Yes,6000,Sales,2,3600,743.295848,743.295848,38.6,2921.504761,1525.191696,0
2,BR,SÃ£o Paulo,ZA,Johannesburg,10,Economy Flight,Conference/Exhibition,No,9000,Services,1,450,1053.713528,1053.713528,51.4,743.646219,2158.827056,0
3,DE,Berlin,FR,Paris,12,Business Class Flight,Customer Visit,No,10000,Executive Management,1,3450,196.262703,196.262703,6.7,3343.160260,399.225407,0
4,BR,SÃ£o Paulo,ZA,Johannesburg,10,Economy Flight,Internal Business Trip,No,7000,Marketing,2,1500,1053.713528,1053.713528,102.8,2478.820729,2210.227056,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65284,AU,Sydney,DE,Frankfurt,10,Economy Flight,Customer Visit,No,6000,Sales,4,2400,2336.832592,2336.832592,52.8,1327.345854,4726.465184,1
65285,DE,Berlin,ES,Madrid,15,Volkswagen Golf petrol,Customer Visit,No,8000,Executive Management,5,2850,507.512023,523.655278,35.0,571.126151,1066.167301,0
65286,BR,SÃ£o Paulo,US,Miami,12,Business Class Flight,Customer Visit,Yes,10000,Sales,5,2100,2700.226755,2700.226755,80.5,1655.244071,5480.953510,1
65287,AU,Sydney,AU,Melbourne,13,BMW 3 diesel,Customer Visit,No,8000,Marketing,5,1800,248.764540,247.991202,175.0,464.466292,671.755742,0
65288,AU,Sydney,DE,Frankfurt,12,Business Class Flight,Customer Visit,Yes,9000,Sales,2,2850,6776.567059,6776.567059,26.4,1576.223201,13579.534118,1

In [ ]:
cat_cols = df.select_dtypes(include=['category','object']).columns
cat_cols

:

In [8]:
df_encoded = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=True,
    dtype=int
)

In [9]:
df_encoded

,ShippingType,EntitiyCode,HotelNights,NetCosts,Departure_CO2e,Return_CO2e,Hotel_CO2e,Spend_CO2e,TotalCO2e,HighCarbon,...,BusinessUnit_Finance,BusinessUnit_Legal,BusinessUnit_Marketing,BusinessUnit_Office Management,BusinessUnit_Operations,BusinessUnit_Product Management,BusinessUnit_Sales,BusinessUnit_Services,BusinessUnit_Sustainability,BusinessUnit_Value Engineering
0,12,9000,1,900,1565.121857,1565.121857,58.9,1472.279257,3189.143714,0,...,0,0,0,0,0,0,0,1,0,0
1,11,6000,2,3600,743.295848,743.295848,38.6,2921.504761,1525.191696,0,...,0,0,0,0,0,0,1,0,0,0
2,10,9000,1,450,1053.713528,1053.713528,51.4,743.646219,2158.827056,0,...,0,0,0,0,0,0,0,1,0,0
3,12,10000,1,3450,196.262703,196.262703,6.7,3343.160260,399.225407,0,...,0,0,0,0,0,0,0,0,0,0
4,10,7000,2,1500,1053.713528,1053.713528,102.8,2478.820729,2210.227056,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65284,10,6000,4,2400,2336.832592,2336.832592,52.8,1327.345854,4726.465184,1,...,0,0,0,0,0,0,1,0,0,0
65285,15,8000,5,2850,507.512023,523.655278,35.0,571.126151,1066.167301,0,...,0,0,0,0,0,0,0,0,0,0
65286,12,10000,5,2100,2700.226755,2700.226755,80.5,1655.244071,5480.953510,1,...,0,0,0,0,0,0,1,0,0,0
65287,13,8000,5,1800,248.764540,247.991202,175.0,464.466292,671.755742,0,...,0,0,1,0,0,0,0,0,0,0
65288,12,9000,2,2850,6776.567059,6776.567059,26.4,1576.223201,13579.534118,1,...,0,0,0,0,0,0,1,0,0,0

In [23]:
#trip_ids = df["tripID"]

X_train, X_test, y_train, y_test, id_train, id_test = train_test_split(
    X,
    y,
    trip_ids,
    test_size=0.2,
    random_state=42
)

In [11]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\dell\anaconda3\lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

In [25]:
pred

array([0, 0, 0, ..., 0, 0, 1])

In [26]:
print(len(trip_ids))
print(len(pred))

65289
13058

In [14]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0

In [28]:
results = pd.DataFrame({
    "tripID": trip_ids.loc[X_test.index].values,
    "Predicted": pred
})

results.to_csv("predictions.csv", index=False)

In [29]:
import os
print(os.getcwd())

C:\Users\DELL\Desktop\anaconda

In [30]:
import joblib
joblib.dump(model, "model.pkl")

['model.pkl']

In [32]:
import joblib



# Save the training columns
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [33]:

X.columns

Index(['ShippingType', 'EntitiyCode', 'HotelNights', 'NetCosts',
       'Departure_CO2e', 'Return_CO2e', 'Hotel_CO2e', 'Spend_CO2e',
       'TotalCO2e', 'DepartureLocationCountry_BR',
       'DepartureLocationCountry_CN', 'DepartureLocationCountry_DE',
       'DepartureLocationCountry_ES', 'DepartureLocationCountry_JP',
       'DepartureLocationCountry_MX', 'DepartureLocationCountry_US',
       'DepartureLocationCountry_ZA', 'DepartureLocationCity_Berlin',
       'DepartureLocationCity_Cape Town', 'DepartureLocationCity_Fukuoka',
       'DepartureLocationCity_Hamburg', 'DepartureLocationCity_Madrid',
       'DepartureLocationCity_Mexico City', 'DepartureLocationCity_New York',
       'DepartureLocationCity_Sydney', 'DepartureLocationCity_SÃ£o Paulo',
       'ArrivalLocationCountry_AU', 'ArrivalLocationCountry_CA',
       'ArrivalLocationCountry_CN', 'ArrivalLocationCountry_DE',
       'ArrivalLocationCountry_ES', 'ArrivalLocationCountry_FR',
       'ArrivalLocationCountry_GB', 'ArrivalLocationCountry_IN',
       'ArrivalLocationCountry_IT', 'ArrivalLocationCountry_JP',
       'ArrivalLocationCountry_MX', 'ArrivalLocationCountry_NL',
       'ArrivalLocationCountry_NZ', 'ArrivalLocationCountry_PT',
       'ArrivalLocationCountry_RU', 'ArrivalLocationCountry_SG',
       'ArrivalLocationCountry_TR', 'ArrivalLocationCountry_US',
       'ArrivalLocationCountry_ZA', 'ArrivalLocationCity_Auckland',
       'ArrivalLocationCity_Beijing', 'ArrivalLocationCity_Berlin',
       'ArrivalLocationCity_Brisbane', 'ArrivalLocationCity_Buenos Aires',
       'ArrivalLocationCity_Frankfurt', 'ArrivalLocationCity_Istanbul',
       'ArrivalLocationCity_Johannesburg', 'ArrivalLocationCity_Lisbon',
       'ArrivalLocationCity_London', 'ArrivalLocationCity_Los Angeles',
       'ArrivalLocationCity_Madrid', 'ArrivalLocationCity_Melbourne',
       'ArrivalLocationCity_Mexico City', 'ArrivalLocationCity_Miami',
       'ArrivalLocationCity_Moscow', 'ArrivalLocationCity_New Delhi',
       'ArrivalLocationCity_New York', 'ArrivalLocationCity_Paris',
       'ArrivalLocationCity_Perth', 'ArrivalLocationCity_Rome',
       'ArrivalLocationCity_Singapore', 'ArrivalLocationCity_Sydney',
       'ArrivalLocationCity_Tokyo', 'ArrivalLocationCity_Toronto',
       'ShippingTypeDescription_BMW 3 plugin hybrid',
       'ShippingTypeDescription_Business Class Flight',
       'ShippingTypeDescription_Economy Flight',
       'ShippingTypeDescription_Fiat 500 electric',
       'ShippingTypeDescription_First Class Flight',
       'ShippingTypeDescription_Train',
       'ShippingTypeDescription_Volkswagen Golf diesel',
       'ShippingTypeDescription_Volkswagen Golf petrol',
       'Purpose_Customer Visit', 'Purpose_Enablement',
       'Purpose_Internal Business Trip', 'Purpose_Partner Visit',
       'OutOfPolicy_Yes', 'BusinessUnit_Ecosystem', 'BusinessUnit_Engineering',
       'BusinessUnit_Executive Management', 'BusinessUnit_Finance',
       'BusinessUnit_Legal', 'BusinessUnit_Marketing',
       'BusinessUnit_Office Management', 'BusinessUnit_Operations',
       'BusinessUnit_Product Management', 'BusinessUnit_Sales',
       'BusinessUnit_Services', 'BusinessUnit_Sustainability',
       'BusinessUnit_Value Engineering'],
      dtype='object')

In [34]:
import joblib

joblib.dump(model, "xgboost_model.pkl")

['xgboost_model.pkl']